Chapter4 Signup & Footer
MoriguchiHinata/frontend-basic-site pull request #3
Opened 2023-07-23 06:52 UTC by MoriguchiHinata

よろしくお願いします。

2023-07-24 05:51 UTC, Hikari-Tanaka-pikka reviewed
1点コメントしました!
ほぼ完璧です!!

2023-07-24 05:51 UTC, Hikari-Tanaka-pikka commented on index.html
> +            お申し込みは下記フォームからどうぞ！
Figmaの画像のようにbrタグで改行いれましょ!
<img width="740" alt="スクリーンショット 2023-07-24 14 46 37" src="https://github.com/MoriguchiHinata/frontend-basic-site/assets/109089533/3b324965-5b4e-4229-a84e-c3104bdfde6e">

2023-07-24 16:14 UTC, higashiji2000 requested changes
HTML, CSS ともにきれいに書けていていい感じです 🙌 
フォームの作り方に関してもGoodです 👍 
細かい点コメントしたので修正お願いします！

2023-07-24 16:14 UTC, higashiji2000 commented on index.html
> +        <button class="signup-button" form="signup-form" type="submit">
![image](https://github.com/MoriguchiHinata/frontend-basic-site/assets/83479175/710e0b52-2b34-4a48-97a0-772f90c68404)
`button` のデフォルトのスタイルである border が付与されてしまっています。
CSSで上書きしましょう！

2023-07-24 16:14 UTC, higashiji2000 commented on style.css
> +}
【修正不要】
`.courses-button` と同じスタイルが含まれていると思うので、共通のプロパティは別クラスに切り出す等すると共通化できます。
最終課題ではそこまで気にしなくて大丈夫ですが、繰り返しを避けるDRY原則を頭の片隅においておくと、必要になったときに良いコードの指針となるかと思います！

参考：https://xn--97-273ae6a4irb6e2hsoiozc2g4b8082p.com/%E3%82%A8%E3%83%83%E3%82%BB%E3%82%A4/DRY%E5%8E%9F%E5%89%87/

2023-07-24 16:14 UTC, higashiji2000 commented on style.css
> +}
CSSのセレクタの詳細度は可能な限り揃えると、後から上書きがしやすくてカオスになりづらいです。
IDセレクタは詳細度を一段階上げてしまうので、可能であればクラスセレクタで記述するのがおすすめです！

2023-07-24 16:14 UTC, higashiji2000 commented on index.html
> +          />
細かいですが、 `button` をフォームの送信ボタンとして機能させるためには `form` 要素の子要素として配置する必要があります。
また、 `button` の閉じタグがなさそうなので修正お願いします！

2023-07-25 02:33 UTC, MoriguchiHinata commented on index.html
> +          />
buttonのform属性に送信したいフォームのidを渡しているのですが、これでは送信できないのでしょうか。
以下のURLを参考にしました。
https://developer.mozilla.org/ja/docs/Web/HTML/Element/button

2023-07-26 01:40 UTC, higashiji2000 approved these changes
LGTM🌻

2023-07-26 01:40 UTC, higashiji2000 commented on index.html
> +          />
いけますね！
この仕様知りませんでした🙏
MDNで確認しているの素晴らしいです！！

2023-07-26 01:40 UTC, higashiji2000 commented on index.html
> +              placeholder="エドワード ヴァン 太郎"
前回コメント漏れていましたが、実際に送信する（クエリに含める）ためには `name` 属性が必要なのでお気をつけください！

2023-07-26 11:43 UTC, merged